
using UnityEngine;
using UnityEditor;
using System;

namespace TerrainGeneratorAsset
{
    public static class EditorNoisePreviewer
    {
        public static void DrawNoisePreview(TerrainConfigSO terrainConfig, Func<float,float,float> noiseFunc)
        {
            // Draw Texture Preview
            const int texPreviewLength = 200;

            Rect outerBox = GUILayoutUtility.GetRect(
                texPreviewLength,
                texPreviewLength,
                GUILayout.ExpandWidth(true)
            );

            float aspect = terrainConfig.terrainDimensions.z
                         / terrainConfig.terrainDimensions.x;

            Rect previewRect = ScaleRectToFit(outerBox, aspect);

            Texture2D tex = GeneratePreviewTexture(terrainConfig, noiseFunc, texPreviewLength);

            EditorGUI.DrawPreviewTexture(
                previewRect,
                tex,
                null,
                ScaleMode.ScaleAndCrop
            );
        }

        private static Texture2D GeneratePreviewTexture(TerrainConfigSO terrainConfig, Func<float,float,float> noiseFunc, int texWidth)
        {
            var tex = new Texture2D(texWidth, texWidth, TextureFormat.RGBA32, false);

            float pixelLengthX = terrainConfig.terrainDimensions.x / (texWidth - 1);
            float pixelLengthZ = terrainConfig.terrainDimensions.z / (texWidth - 1);

            Color32[] pixels = new Color32[texWidth * texWidth];

            for (int i = 0; i < texWidth; i++)
                for (int j = 0; j < texWidth; j++)
                {
                    float value = Mathf.Clamp01(noiseFunc(i * pixelLengthX, j * pixelLengthZ));
                    pixels[j + i * texWidth] = new Color(value, value, value, 1f);
                }

            tex.SetPixels32(pixels);
            tex.Apply(false);

            return tex;
        }

        private static Rect ScaleRectToFit(Rect outer, float aspect)
        // This function was generated by ChatGPT
        {
            float outerAspect = outer.width / outer.height;

            if (outerAspect > aspect)
            {
                // box too wide → pillarbox
                float width = outer.height * aspect;
                float x = outer.x + (outer.width - width) * 0.5f;
                return new Rect(x, outer.y, width, outer.height);
            }
            else
            {
                // box too tall → letterbox
                float height = outer.width / aspect;
                float y = outer.y + (outer.height - height) * 0.5f;
                return new Rect(outer.x, y, outer.width, height);
            }
        }
    }
}