
using TerrainGeneratorAsset;
using UnityEditor;
using UnityEngine;
using System;
using System.Collections.Generic;

[CustomEditor(typeof(NoiseLayerSO))]
public class NoiseLayerSOEditor : Editor
{
    private TerrainConfigSO m_terrainConfig;
    public override void OnInspectorGUI()
    {
        serializedObject.Update();
        NoiseLayerSO noiseLayer = target as NoiseLayerSO;

        // List Serialized Fields
        var it = serializedObject.GetIterator();
        bool enterChildren = true;
        while(it.NextVisible(enterChildren))
        {
            if (it.propertyPath == "m_Script") continue;
            EditorGUILayout.PropertyField(it, includeChildren: true);
            enterChildren = false;
        }

        EditorGUILayout.Space();

        // Draw Texture Preview
        const int texPreviewLength = 200;

        Rect outerBox = GUILayoutUtility.GetRect(
            texPreviewLength,
            texPreviewLength,
            GUILayout.ExpandWidth(true)
        );

        float aspect = m_terrainConfig.terrainDimensions.z
                     / m_terrainConfig.terrainDimensions.x;

        Rect previewRect = ScaleRectToFit(outerBox, aspect);

        Texture2D tex = GeneratePreviewTexture(noiseLayer, texPreviewLength);

        EditorGUI.DrawPreviewTexture(
            previewRect,
            tex,
            null,
            ScaleMode.ScaleAndCrop
        );

        serializedObject.ApplyModifiedProperties(); 
    }
    private Rect ScaleRectToFit(Rect outer, float aspect)
        // This function was generated by ChatGPT
    {
        float outerAspect = outer.width / outer.height;

        if (outerAspect > aspect)
        {
            // box too wide → pillarbox
            float width = outer.height * aspect;
            float x = outer.x + (outer.width - width) * 0.5f;
            return new Rect(x, outer.y, width, outer.height);
        }
        else
        {
            // box too tall → letterbox
            float height = outer.width / aspect;
            float y = outer.y + (outer.height - height) * 0.5f;
            return new Rect(outer.x, y, outer.width, height);
        }
    }

    private Texture2D GeneratePreviewTexture(NoiseLayerSO noise, int texWidth)
    {
        var tex = new Texture2D(texWidth, texWidth, TextureFormat.RGBA32, false);

        Func<float, float, float> sampler = noise.Evaluate;

        float pixelLengthX = m_terrainConfig.terrainDimensions.x / (texWidth - 1);
        float pixelLengthZ = m_terrainConfig.terrainDimensions.z / (texWidth - 1);

        Color32[] pixels = new Color32[texWidth * texWidth];

        for (int i = 0; i < texWidth; i++)
            for (int j = 0; j < texWidth; j++)
            {
                float value = Mathf.Clamp01(sampler(i * pixelLengthX, j * pixelLengthZ));
                pixels[j + i * texWidth] = new Color(value, value, value, 1f);
            }

        tex.SetPixels32(pixels);
        tex.Apply(false);

        return tex;
    }

    public void SetTerrainConfigSO(TerrainConfigSO terrainConfig)
    {
       m_terrainConfig = terrainConfig; 
    }

}